name: CI

on:
  push:
  release:
    types: [ published ]

env:
  # Update this to force cache reset
  CACHE_KEY: ${{ secrets.CACHE_KEY }}

  PHP_VERSION: 7.4
  PHP_SECURITY_CHECKER_VERSION: 1.2.0

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: vendor/
          key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Cache PHP CS Fixer
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.dist.php
          key: cache-${{ env.CACHE_KEY }}-phpcsfixer

      - name: Cache PHPStan
        uses: actions/cache@v3
        with:
          path: var/phpstan-tmp/
          key: cache-${{ env.CACHE_KEY }}-phpstan

      - uses: ./.github/actions/setup-composer

      - name: PHP Coding Standards Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --no-interaction -v

      - name: Lint YAML files
        run: bin/console lint:yaml config --parse-tags

      - name: Lint container
        run: bin/console lint:container

      - name: PHPStan - PHP Static Analysis Tool
        run: vendor/bin/phpstan analyse

      - name: Local PHP Security Checker
        run: |-
          curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v${PHP_SECURITY_CHECKER_VERSION}/local-php-security-checker_${PHP_SECURITY_CHECKER_VERSION}_linux_$(dpkg --print-architecture) --output ./local-php-security-checker
          chmod +x ./local-php-security-checker

          ./local-php-security-checker

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: vendor/
          key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('**/composer.lock') }}

      - run: |-
          make build
          make phpunit
